### User register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "nombre": "prueba",
  "documento": "12345",
  "correo": "prueba@gmail.com",
  "contrasena": "1234567"
}
### User login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "correo": "prueba@gmail.com",
  "contrasena": "1234567"
}

### Verify user
GET http://localhost:3000/api/v1/auth/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEzLCJ1c2VybmFtZSI6InBydWViYSIsImlhdCI6MTc1MTY3MDA4NywiZXhwIjoxNzU0MjYyMDg3fQ.GhdRwWAeKrn3X4QHAqDoK1tep-jxgL7j6T2L9kqz4eI

### Create Book
POST http://localhost:3000/api/v1/inventory/create
Content-Type: application/json

{
  "nombre": "Alicia en el pais de las maravillas",
  "autor": "Lewis Carrol",
  "cantidad": 20,
  "portada_url": "https://images.cdn1.buscalibre.com",
  "anio": 2016,
  "editorial": "Edelvives",
  "genero": "Misterio",
  "sistema_dewey": "109",
  "ubicacion": "Estanteria 2"
}
### Show catalog 
GET http://localhost:3000/api/v1/catalog/
Content-Type: application/json

### Filtro libros
GET http://localhost:3000/api/v1/catalog/year/2016
Content-Type: application/json
