### User register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "nombre": "prueba",
  "documento": "12345",
  "correo": "prueba@gmail.com",
  "contrasena": "1234567"
}
### User login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "correo": "prueba@gmail.com",
  "contrasena": "1234567"
}

### Mostrar catalogo
GET http://localhost:3000/api/v1/catalog/
Content-Type: application/json

### Filtro libros
GET http://localhost:3000/api/v1/catalog/year/2000
Content-Type: application/json
