### User register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "nombre": "prueba",
  "documento": "12345",
  "correo": "prueba@gmail.com",
  "contrasena": "1234567"
}
### user login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "correo": "prueba@gmail.com",
  "contrasena": "1234567"
}
